<?php
/**
 * Plugin Name:     Hexagon Automation (Fixed AJAX)
 * Plugin URI:      https://hex-net.eu/hexagon-automation
 * Description:     AI-powered automation with fixed AJAX handling - v3.0.3
 * Version:         3.0.3
 * Requires at least: 5.0
 * Requires PHP: 7.4
 * Tested up to:    6.4
 * Author:          Hexagon Technology
 */

// Exit if accessed directly
if (!defined('ABSPATH')) {
    exit;
}

// Plugin guards
if (function_exists('hexagon_automation_main')) {
    add_action('admin_notices', function() {
        echo '<div class="notice notice-error"><p><strong>Hexagon Automation:</strong> Wykryto duplikację plugina. Deaktywuj inne wersje.</p></div>';
    });
    return;
}

// Constants
define('HEXAGON_FIXED_VERSION', '3.0.3');
define('HEXAGON_FIXED_PATH', plugin_dir_path(__FILE__));
define('HEXAGON_FIXED_URL', plugin_dir_url(__FILE__));

// Main function
function hexagon_automation_main() {
    
    // 1. BASIC SAFETY FUNCTIONS
    if (!function_exists('hexagon_log')) {
        function hexagon_log($action, $context, $level = 'info') {
            if (defined('WP_DEBUG_LOG') && WP_DEBUG_LOG) {
                error_log("Hexagon [$level]: $action - $context");
            }
            
            global $wpdb;
            $table_name = $wpdb->prefix . 'hex_logs';
            
            // Safe insert - nie crashuj jeśli tabela nie istnieje
            if ($wpdb->get_var("SHOW TABLES LIKE '$table_name'") == $table_name) {
                $wpdb->insert(
                    $table_name,
                    [
                        'action' => $action,
                        'context' => $context,
                        'level' => $level,
                        'created_at' => current_time('mysql')
                    ]
                );
            }
            return true;
        }
    }
    
    if (!function_exists('hexagon_get_option')) {
        function hexagon_get_option($option_name, $default = '') {
            return get_option($option_name, $default);
        }
    }
    
    // 2. SAFE AJAX HANDLERS
    add_action('wp_ajax_hexagon_debug_test', function() {
        wp_send_json_success([
            'message' => '✅ AJAX działa poprawnie!',
            'timestamp' => current_time('mysql'),
            'version' => HEXAGON_FIXED_VERSION,
            'wp_version' => get_bloginfo('version'),
            'php_version' => PHP_VERSION
        ]);
    });
    
    add_action('wp_ajax_hexagon_ai_generate_safe', function() {
        try {
            // Sprawdź nonce (opcjonalnie)
            if (isset($_POST['nonce']) && !wp_verify_nonce($_POST['nonce'], 'hexagon_ai_nonce')) {
                wp_send_json_error(['message' => 'Błąd bezpieczeństwa']);
                return;
            }
            
            $provider = sanitize_text_field($_POST['provider'] ?? 'test');
            $prompt = sanitize_textarea_field($_POST['prompt'] ?? 'Hello World');
            
            // Symulacja AI (bez external API calls które mogą crashować)
            wp_send_json_success([
                'content' => "✅ Test content generated by $provider\n\nPrompt: $prompt\n\nThis is a safe test without external API calls.",
                'provider' => $provider,
                'timestamp' => current_time('mysql')
            ]);
            
        } catch (Exception $e) {
            hexagon_log('AI Error', $e->getMessage(), 'error');
            wp_send_json_error(['message' => $e->getMessage()]);
        }
    });
    
    // 3. ADMIN MENU
    add_action('admin_menu', function() {
        add_menu_page(
            'Hexagon Fixed',
            'Hexagon Fixed',
            'manage_options',
            'hexagon-fixed',
            function() {
                ?>
                <div class="wrap">
                    <h1>🔧 Hexagon Automation - Fixed Version</h1>
                    
                    <div class="notice notice-info">
                        <p><strong>Wersja naprawiona 3.0.2</strong> - rozwiązuje błędy HTTP 500 w admin-ajax.php</p>
                    </div>
                    
                    <h2>🧪 Testy AJAX</h2>
                    <table class="widefat">
                        <tr>
                            <td><strong>Debug Test:</strong></td>
                            <td><button class="button" onclick="testAjax('hexagon_debug_test')">Test Basic AJAX</button></td>
                            <td id="result-debug">Gotowy do testu</td>
                        </tr>
                        <tr>
                            <td><strong>AI Test:</strong></td>
                            <td><button class="button" onclick="testAI()">Test AI Generation</button></td>
                            <td id="result-ai">Gotowy do testu</td>
                        </tr>
                    </table>
                    
                    <h2>📊 System Info</h2>
                    <table class="widefat">
                        <tr><td><strong>Plugin Version:</strong></td><td><?php echo HEXAGON_FIXED_VERSION; ?></td></tr>
                        <tr><td><strong>WordPress:</strong></td><td><?php echo get_bloginfo('version'); ?></td></tr>
                        <tr><td><strong>PHP:</strong></td><td><?php echo PHP_VERSION; ?></td></tr>
                        <tr><td><strong>Memory:</strong></td><td><?php echo ini_get('memory_limit'); ?></td></tr>
                        <tr><td><strong>WP Debug:</strong></td><td><?php echo defined('WP_DEBUG') && WP_DEBUG ? '✅ ON' : '❌ OFF'; ?></td></tr>
                    </table>
                    
                    <h2>📋 Rezultat testów</h2>
                    <textarea id="test-results" style="width: 100%; height: 200px;" readonly>Wyniki testów będą tutaj...</textarea>
                    
                    <script>
                    function testAjax(action) {
                        document.getElementById('result-debug').innerHTML = '⏳ Testing...';
                        
                        jQuery.post(ajaxurl, {
                            action: action
                        })
                        .done(function(response) {
                            document.getElementById('result-debug').innerHTML = '✅ SUCCESS';
                            updateResults('Debug Test: SUCCESS\n' + JSON.stringify(response, null, 2));
                        })
                        .fail(function(xhr, status, error) {
                            document.getElementById('result-debug').innerHTML = '❌ FAILED';
                            updateResults('Debug Test: FAILED\nError: ' + error + '\nStatus: ' + xhr.status + '\nResponse: ' + xhr.responseText);
                        });
                    }
                    
                    function testAI() {
                        document.getElementById('result-ai').innerHTML = '⏳ Testing...';
                        
                        jQuery.post(ajaxurl, {
                            action: 'hexagon_ai_generate_safe',
                            provider: 'test',
                            prompt: 'Test prompt from dashboard'
                        })
                        .done(function(response) {
                            document.getElementById('result-ai').innerHTML = '✅ SUCCESS';
                            updateResults('AI Test: SUCCESS\n' + JSON.stringify(response, null, 2));
                        })
                        .fail(function(xhr, status, error) {
                            document.getElementById('result-ai').innerHTML = '❌ FAILED';
                            updateResults('AI Test: FAILED\nError: ' + error + '\nStatus: ' + xhr.status + '\nResponse: ' + xhr.responseText);
                        });
                    }
                    
                    function updateResults(text) {
                        const textarea = document.getElementById('test-results');
                        textarea.value = new Date().toLocaleString() + ':\n' + text + '\n\n' + textarea.value;
                    }
                    </script>
                </div>
                <?php
            },
            'dashicons-admin-tools'
        );
    });
    
    // 4. ACTIVATION HOOK
    register_activation_hook(__FILE__, function() {
        global $wpdb;
        
        // Create logs table safely
        $table_name = $wpdb->prefix . 'hex_logs';
        
        $charset_collate = $wpdb->get_charset_collate();
        
        $sql = "CREATE TABLE $table_name (
            id mediumint(9) NOT NULL AUTO_INCREMENT,
            action varchar(100) NOT NULL,
            context text,
            level varchar(20) DEFAULT 'info',
            created_at datetime DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (id)
        ) $charset_collate;";
        
        require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
        dbDelta($sql);
        
        hexagon_log('Plugin Activated', 'Hexagon Fixed v' . HEXAGON_FIXED_VERSION, 'success');
        
        add_option('hexagon_fixed_notice', 'Hexagon Automation Fixed v' . HEXAGON_FIXED_VERSION . ' activated successfully!');
    });
    
    // 5. ADMIN NOTICE
    add_action('admin_notices', function() {
        $notice = get_option('hexagon_fixed_notice');
        if ($notice) {
            echo '<div class="notice notice-success is-dismissible">';
            echo '<p><strong>✅ ' . esc_html($notice) . '</strong></p>';
            echo '<p>Przejdź do <a href="' . admin_url('admin.php?page=hexagon-fixed') . '">Hexagon Fixed</a> aby przetestować AJAX.</p>';
            echo '</div>';
            delete_option('hexagon_fixed_notice');
        }
    });
}

// Initialize
add_action('plugins_loaded', 'hexagon_automation_main');